[build]
target = "thumbv7em-none-eabi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.thumbv7em-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F767ZITx"
